FROM node:18-alpine
WORKDIR /app

# Copy package files
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# The Next.js dev server runs on port 3000
EXPOSE 3000

# The command to start the development server
CMD ["npm", "run", "dev"]
